## platformConfig contains information about the environment on which the Chart is being installed
## These values are expected be updated during the platform installation stage
platformConfig:
  ## Container registry for all images involved in the chart
  imageRegistry: hub.byted.org
  ## Container repository for platform components
  imageRepositoryRelease: infcprelease
  ## Platform-wide image pull policy
  imagePullPolicy: Always
  ## Image pull secret names
  imagePullSecret: []

labels: {}

podLabels: {}

podAnnotations: {}

nodeSelector: {}

tolerations: []

image:
  name: vetes-api
  tag: v1.0.0

replicaCount: 2

priorityClassName: ""

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi

securityContext:
  enabled: true
  runAsUser: 65534  # nobody
  runAsGroup: 65534 # nogroup
  fsGroup: 65534    # nogroup

service:
  type: ClusterIP
  port: 8080
  metricsPort: 9090
  annotations: {}
  labels: {}

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: ""
      paths:
        - path: /vetes-api/(.*)
          pathType: ImplementationSpecific
  tls: []

hardAntiAffinity: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

prometheus:
  labels: {}
  interval: 15s
  scrapeTimeout: 10s

db:
  type: mysql
  mysql:
    username: ""
    password: ""
    host: ""
    port: 3306
    database: vetes

log:
  level: info
  outputPath: app.log

normalize:
  executorBasePath: "/cromwell-executions/"
  diskGB:
    enable: true
    min: 20
    max: 8192
    isInteger: true
  bootDiskGB:
    enable: true
    min: 40
    max: 100
  gpu:
    enable: true
    isInteger: true
