apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vetes-api.fullname" . }}
  labels:
    {{- include "vetes-api.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vetes-api.fullname" . }}
  labels:
    {{- include "vetes-api.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vetes-api.fullname" . }}
  labels:
    {{- include "vetes-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vetes-api.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vetes-api.fullname" . }}
    namespace: {{ .Release.Namespace }}
